[flags]
# Process tree
tree = true
tree_collapse = false
process_command = true

# Display
battery = true
show_table_scroll_position = true
enable_cache_memory = true

# Network units
network_use_bytes = true
network_use_binary_prefix = true

# CPU
unnormalized_cpu = true
